Re-include UTR length calculations and plot
zavolanlab/PAQR_KAPAC pull request #22
Opened 2021-10-20 17:02 UTC by ninsch3000

2021-10-28 08:23 UTC, AngryMaciek commented
> _No description provided._

Please provide descriptions of PRs; bullet points with changes are OK

2021-10-28 09:01 UTC, AngryMaciek requested changes
Generally OK; minor corrections required, mostly formatting

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/README.md
> +- weigthed_avg_exon_lengths.pdf
I am not sure if it makes sense to list a intermediate files<?>
If you think this is a good idea then OK.

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/scripts/infer-pas-expression.py
> +
I assume that the header is the same as for _expressions_ file, correct? That is good then.

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +    input:
rule header does not match other rules, please adjust the format

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +    ##LOCAL##
header does not match the rest, please adjust format

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +        '''
GitHub complains

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +            "PAQ_exon_lengths.stdout.log"
`PAQ` + rule name

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +            "PAQ_exon_lengths.stderr.log"
`PAQ` + rule name

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +            "PAQ_exon_lengths.benchmark.log"
`PAQ` + rule name . benchmark

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +            "PAQ_exon_lenghts.log"
`PAQ` + rule name

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +            "PAQ_plot_exon_lenghts.log"
`PAQ` + rule name

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +            "PAQ_plot_exon_lengths.stdout.log"
`PAQ` + rule name

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +            "PAQ_plot_exon_lengths.stderr.log"
`PAQ` + rule name

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/Snakefile
> +            "PAQ_plot_exon_lengths.benchmark.log"
`PAQ` + rule name .  benchmark

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/env/r.yml
> +...
GitHub complains

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/scripts/calculate-average-3pUTR-length.py
> +#!/usr/bin/env python
If you are running a script in _conda_ then specifying a python interpreter out of the conda env does not make sense!
Remove the shebang line.

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/scripts/calculate-average-3pUTR-length.py
> +"""
?

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/scripts/calculate-average-3pUTR-length.py
> +__license__ = "GPL"
which version?

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/scripts/calculate-average-3pUTR-length.py
> +                    help="path and name of the file with the relative usages")
This script takes the filtered relative usages, right?
I assume that as you added the header to the unfiletered relative usages file but the header is propagated here too? Then I guess you modified this original script to account for the headers too?

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/scripts/filter-tables.py
> -        samples = expression.columns.values[10:]
we dont need this variable anymore?

2021-10-28 09:01 UTC, AngryMaciek commented on PAQR2/PAQR/scripts/plot-ecdfs.R
> +suppressPackageStartupMessages(library("optparse"))
Missing info lines about the author, license, email etc.

2021-11-04 16:00 UTC, ninsch3000 commented on PAQR2/PAQR/scripts/calculate-average-3pUTR-length.py
> +                    help="path and name of the file with the relative usages")
yes, see line 55

2021-11-04 16:01 UTC, ninsch3000 commented on PAQR2/PAQR/scripts/filter-tables.py
> -        samples = expression.columns.values[10:]
Never needed it

2021-11-04 16:07 UTC, ninsch3000 commented on PAQR2/PAQR/scripts/plot-ecdfs.R
> +suppressPackageStartupMessages(library("optparse"))
Good point, but I don't know those

2021-11-04 16:51 UTC, AngryMaciek commented on PAQR2/PAQR/scripts/plot-ecdfs.R
> +suppressPackageStartupMessages(library("optparse"))
I think Ralf is the autor, we can set MIT license and Mihaela can be the contact person w/ email.

2021-11-05 11:31 UTC, closed without merging